---
-
  hosts: all
  name: "Gather Facts"
  become_user: root

  tasks:
    - name: Check if Swarm has already been Initialized
      shell: docker node ls
      register: swarm_status
      ignore_errors: true


    - name: Swarm Init
      command: docker swarm init --advertise-addr={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:2377
      when: swarm_status.rc != 0
      run_once: true

    - name: Get Worker Token
      command: docker swarm join-token worker -q
      register: worker_token

    - name: Show Worker Token
      debug:
        var: worker_token.stdout

    - name: Get Manager Token
      command: docker swarm join-token manager -q
      register: manager_token

    - name: Show Manager Token 
      debug:
        var: manager_token.stdout
