---
-
  hosts: docker_slave
  name: "Gather Facts"
  become_user: root

  tasks:
    - name: Join worker to Swarm
      command: "docker swarm join --token {{ hostvars['docker_manager']['worker_token']['stdout'] }} {{ hostvars[docker_manager]['ansible_default_ipv4']['address'] }}:2377"
      register: worker

    - name: Show Results
      debug: var=worker.stdout

    - name: Show Errors
      debug: var=worker.stderr
